default: &default
  adapter: postgresql
  username: <%= ENV.fetch("DB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'postgres' } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
development:
  <<: *default
  database: onebitcode_development

test:
  <<: *default
  database: onebitcode_test

production:
  <<: *default
  database: onebitcode_production